### ISSUE TITLE
Improve definition of "absolutism"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#108]
05967204-n (Interlingual Index: i68136)
(n) absolutism 
> the doctrine of an absolute being

This probably refers to philosophical absolutism https://en.wikipedia.org/wiki/Absolute_(philosophy) but is is unclear

**Comment by jmccrae** [comment]
this doesn't seem to refer to any existing concept. Perhaps it should be removed? Any other opinions?

**Comment by arademaker** [comment]
For me, it is related to the wikipedia page. So I vote to keep.

**Comment by arademaker** [comment]
The problem is that 


    05958337-n absolutism 
        (the doctrine of an absolute being)

    14443912-n tyranny, despotism, absolutism 
        (dominance through threat of punishment and violence)

    06213688-n totalism, totalitarianism, absolutism 
        (the principle of complete and unrestricted power in government)

    08440630-n absolutism, Caesarism, monocracy, shogunate, tyranny, dictatorship, totalitarianism, one-man_rule, despotism, authoritarianism, Stalinism 
        (a form of government in which the ruler is an absolute dictator (not restricted by a constitution or laws or opposition etc.))

08440630-n seems to be the form of government. But the 06213688-n mention goverment too (is hyponym of ideology). It is hard to distinguish these senses.

**Comment by dcillessen** [comment]
06213688-n refers to the idea of unrestricted power in government rather than its implementation.  In this sense it is related to "ideology" which is the hypernym for a multitude of political ideas like its potential opposites in the forms of ewn-06223643-n "anarchism" and ewn-06229122-n "libertarianism"  

The wording of 06213688-n is a bit unclear though.  In the context of other hyponyms of "ideology," perhaps the definition can be improved by borrowing the wording of other similar synsets.  

ewn-06229122-n "libertarianism" is defined as "an ideological belief in freedom of thought, speech and action." I'd advocate for a new definition for 06213688-n along those lines.  Something like "an ideological belief in the complete and unrestricted power of government"  

@arademaker, do you think this makes the distinction suitably clear?

With regards to 05967204-n, I think we can make the definition more clear by adding some more information to it. I'd suggest something like "the doctrine of an absolute being, often related to idealism in philosophy."

**Comment by Ciara97olo** [comment]
I agree with @dcillessen that this is the best way to move forward
