### ISSUE TITLE
Inclusion of slurs?

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#151]
Princeton WordNet 3.0 contains many racial, homophobic and other slurs that are no longer in 3.1 and hence not in this wordnet. Does the community feel that it would be a good idea to include these words again?

The complete list is:
* abo
* african_american
* afro-american
* amerindian_race
* black_american
* blackamoor
* black_man
* black_person
* black_race
* black_woman
* caucasian_race
* caucasoid_race
* colored
* colored_person
* darkey
* darkie
* darky
* gay_man
* jigaboo
* mayas
* mongolian_race
* mongoloid_race
* negress
* negroid_race
* negro_race
* nigga
* nigger
* nigra
* oriental
* oriental_person
* paleface
* people_of_color
* people_of_colour
* red_indian
* shirtlifter
* slant-eye
* white_people
* white_race
* yellow_man
* yellow_race
* yellow_woman

**Comment by cmbant** [comment]
There are some others (words with other senses), e.g. Uncle Tom, spade.

There were also some general words that disappeared, e.g. "penetralia", "reacquaint".

(I would have thought they should be included; in 3.0 the offensive ones were correctly tagged as such)

**Comment by restinplace** [comment]
I'm confused -- using Princeton's online 3.1 lookup tool, at least, some of these 
are still found, e.g. "Mayas" is now the extended  form of "Maya" rather than being 
standalone:
WN 3.0:  mayas#n#1  Mayas#n#1 -- (an ethnic minority speaking Mayan languages and living in Yucatan and adjacent areas)
WN 3.1: {08501397} [14] S: (n) Maya#2 (an ethnic minority speaking Mayan languages and living in Yucatan and adjacent areas) 

What is and isn't in 3.1 seems awfully inconsistent -- is there any written position on this?

**Comment by jmccrae** [comment]
Mayas appears to be a correction of an error in Princeton WordNet 3.0

The other I will add back using the 3.0 data

**Comment by arademaker** [comment]
I don't think we should add them again. Keep in a separate resource.

**Comment by jmccrae** [comment]
Any else wish to comment? It would be good to reach consensus here

**Comment by dcillessen** [comment]
I think that these offensive terms should be included, but agree as well with 1313ou over in pull [343]([https://github.com/globalwordnet/english-wordnet/pull/343](url)) that
> "offensive term for" should appear in the definition.

Other dictionaries, including Merriam-Webster and Oxford, include offensive terms like these but similarly label them as _offensive_ or _derogatory_.  

Ultimately they are part of the language, and they carry especially significant meaning. The distinction between an offensive term and a non-offensive term is significant in determining things like tone, as well as the stance and opinions of the speaker.

It could be argued that including offensive words in WordNet legitimizes their use; however, by including the distinction that these words are "offensive" or "derogatory" we make the point that their use carries extra, offensive, weight.  It also acknowledges the word's history and its significance in that sense.

**Comment by dcillessen** [comment]
I was reminded when reading this [article](https://www.wired.com/story/viral-app-labels-you-isnt-what-you-think/?mbid=social_twitter&utm_brand=wired&utm_campaign=wired&utm_medium=social&utm_social-type=owned&utm_source=twitter) on Wired that AI bias is a significant issue which continually pops up in discussions around mass data processing, especially around using neural networks.  Since EWN is machine readable, it is important that we keep this issue in mind so that we can avoid unintentionally promoting bias.

**Comment by 1313ou** [comment]
Deep learning is used for prediction and decision making. It is biased when
nn are trained on biased data. Which data they are trained on is the
developer's decision. This is a very different picture here.

**Comment by dcillessen** [comment]
You're absolutely right.  My previous comment intends to point out what is at stake rather than to make an argument about what WN is.  I maintain that the words should be added and categorized to clearly show that they are slurs. Their offensiveness shouldn't be downplayed, especially if WN is used as a basis for another project.

**Comment by 1313ou** [comment]
See https://www.gizmodo.co.uk/2020/07/mit-takes-down-popular-ai-dataset-due-to-racist-misogynistic-content/
to cast some light on the issue. To which I will add you do need a list of slurs to purge it from the dataset.

**Comment by arademaker** [comment]
Sorry, I didn’t understand your last comment @1313ou.

**Comment by 1313ou** [comment]
Simply: one has to have a properly tagged list of slurs if one wants to
purge them from a dataset that a machine is trained on (ultimately
meaning that inclusion is necessary).

**Comment by jmccrae** [comment]
I have discussed this with a few others and I have decided I will implement this one. 

I will use the link `exemplifies` to indicate these linking to 'slur' and in some cases to 'racism' to mark these terms

I will also update the interface at https://en-word.net so that these terms appear hidden at first and users must make an extra click in order to see these terms
