### ISSUE TITLE
WNDB versioning (feature request)

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#163]
I noted different versions of WNDB with the same name. Clearly it is advisable to use a versioning scheme, e.g include a stamp file in the archive. For example

index.noun at line 59 is now
15_may_organization n 1 2 @ ; 1 0 08060805  
used to be (shortly after announcement)
15_may_organization n 1 **3** @ ; 1 0 08060805  
(which is wrong because we have two links, not three)

but I have no reference to version

**Comment by jmccrae** [comment]
The WNDB export is a non-normative version to provide backwards compatibility with previous Princeton WordNet versions, and there have been a few updates as bugs have been reported. I am not sure if we need versions for future releases as we should have a more thorough validation process to ensure that there is only a single version.

I am going to leave this open if there are any comments on this

**Comment by ekaf** [comment]
Wouldn't it be more appropriate to call the 2019 version a "developers preview" rather than a "release"? 
The risk is that users expect a "release" to be usable, which is still not really the case, since the relatively few new lemmas have not yet received proper identifiers. Just taking WN 3.1 synset offsets and calling it "the new ILI", reminds me of "The Emperors New Clothes", because these identifiers remain bound to one particular PWN version.  The MCR did something similar when they adopted the WN 3.0 offsets as their "ILI" : updating to a newer PWN version will still imply changing all the identifiers, which would not be necessary with a stable ILI. The promise to keep WN 3.0 or 3.1 offsets stable through future releases is not convincingly substantiated, and I would not bet that it is desirable or even possible.

**Comment by jmccrae** [comment]
As said, the WNDB version is for backwards compatibility and at some point I hope that we can move the community over to the XML.

For issues with the ILI please report at the ILI repository

https://github.com/globalwordnet/ili

**Comment by 1313ou** [comment]
> I hope that we can move the community over to the XML
The XML is perhaps suitable for academic purposes but not for real applications. It is excessively verbose, lacks conciseness and suffers from redundancy (do you realize the string "The banks %s the check" is to be found 7433 times ?!). Besides XML requires important processing resources to parse... By comparison the WNDB format is not **that** bad : it is a human-readable form, is efficient to parse,  is not that redundant and it works with what looks like tables... The problem of offsets has been popping up for 20 years. It's not stupid to use them as primary keys (they're guaranteed  to be unique and are efficient pointers into a table) but don't ask them to work as version trackers and mean anything outside their context.
Finally if you drop support for WNDB format, that means you're cut off from quality libraries and software (like Mark A Finlayson's JWI library)

**Comment by jmccrae** [comment]
I will also reference Issue #31 here regarding improvements to the XML format

**Comment by 1313ou** [comment]
BTW you'll find here:
https://sourceforge.net/projects/sqlunet/files/5.3.0/android/sqlunet-ewn.db.zip
the unversioned sqlite version of english-wordnet I downloaded ... the other day...

**Comment by ekaf** [comment]
If the XML files in the "src" folder are source files for the Princeton-compatible version, the recently corrected sense keys in index.sense would be expected to result from the dc.identifiers in the XML files. But these have not been corrected yet. 

Does this mean that the wndb version is compiled from different source files than the XML files in the "src" folder?

**Comment by jmccrae** [comment]
Could you give an example. They seem to be in-sync to me.

**Comment by ekaf** [comment]
There are many examples. Here is one, from wn-noun.person.xml:

LexicalEntry id="ewn-John_McCormick-n"
      Lemma writtenForm="John McCormack" partOfSpeech="n"
      Sense id="ewn-John_McCormick-n-11188503-02" n="0" synset="ewn-11188503-n" dc:identifier="john_mccormick%1:18:00::"

But in the latest wndb version, index.sense has only the correct sense key "john_mccormack%1:18:00::"

How can this occur with the "src" folder as the lexicographic source?

**Comment by 1313ou** [comment]
It probably comes from the fact that the conversion tool (presumably gwn-scala-api) does not generate index.sense (see https://github.com/jmccrae/gwn-scala-api/issues/8). So where does index.sense come from ?

**Comment by ekaf** [comment]
> It probably comes from the fact that the conversion tool (presumably gwn-scala-api) does not generate index.sense (see [jmccrae/gwn-scala-api#8](https://github.com/jmccrae/gwn-scala-api/issues/8)). So where does index.sense come from ?

OK, it seems plausible that the XML db could have been produced with gwn-scala-api.
However, according to that project page, the conversion tool uses the WNDB as input and does not (yet?) convert the other way round, so this looks like a "hen and egg" issue, since WNDB is a compiled format (i.e. not a source format). Where is the source then?

**Comment by jmccrae** [comment]
GWN Scala API is used to generate the export. There is an experimental output mode for WNDB.
