### ISSUE TITLE
'rival' as adjective

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#185]
an example from the glosstag corpus:

> a prolonged dogfight over their rival bids for the contract

We don't have a sense for 'rival' as an adjective.

**Comment by vcvpaiva** [comment]
yes, I know of several other cases similar to this. nouns and adjectives are difficult to distinguish. 
I could add them here.

**Comment by arademaker** [comment]
The general guidelines for the glosstag annotation contains:

> The general rule of thumb for deciding whether it is a noun or adjective is to check the sense list first for whether there is an adjective sense corresponding to the word, and, if not, then whether there's a corresponding noun sense. So, "damp" in "damp weather" is an adjective, even though a noun sense exists. And “cotton” in “cotton shirts” is a noun, which is modifying another noun.

>  If there is no adjective sense in WordNet, then you should make sure that it is not truly an adjective that is missing from WordNet. A good clue that you have an adjective is if you try to modify it with "very" or "rather" and it sounds ok: “very/rather favorable conditions” (ok) vs. “very/rather cotton shirts” (not ok). Another good clue is if you can make a comparative or superlative form out of it (“damper/dampest/more favorable/most favorable conditions” are all adjectives, but “cottoner/cottonest/more cotton/most cotton shirts” are not).

> If the tests are not ok (that is, none of “very/rather x” and “x-er/x-est/more x/most x” sound good), then check for a matching noun sense. If there is no matching noun sense, then do not assign any sense. (But see b and c below first regarding present and past participles, since it might be a verb!). If a noun sense does exist, then the word can be considered a noun, and be tagged to the noun sense.

So in that particular case, it seems that could be possible to have an extra modifier/intensifier for the `rival`, making it an adjective modifying the noun. Moreover, the noun sense is not applicable because it is restrict to the sense of a person. See also  https://en.wiktionary.org/wiki/rival#Adjective

**Comment by arademaker** [comment]
So, instead of only lists, that are useful and can be provided as part of a more general issue, I am interested in `lexicographical tests` for improving the annotation process.

**Comment by jmccrae** [comment]
This seems to be a noun to me. My intuition is that "more rival" or "most rival" is incorrect and there is also no predicative ("X is rival") usage either, as such I don't really see the case for 'rival' as an adjective

**Comment by arademaker** [comment]
Hum, so the absence of the predicative use is a test for not be an adjective? If so, that test could have been mentioned in the guidelines, I think. Any reference?

Yes, `rival` is not comparable, according to Wiktionary, but as far as I understood, not all adjectives are comparable. So this test for identifying adjectives is not conclusive.

**Comment by jmccrae** [comment]
Yes, there are also adjectives like 'former' that also fail all these tests too, but they also fail the tests of being other parts-of-speech (e.g., no plural 'formers', not used with article alone "a former" (in this sense)). 

'Rival' is without doubt a noun and I would be conservative and say that its attributive usage is as a noun rather than an adjective.

**Comment by arademaker** [comment]
So https://en.wiktionary.org/wiki/rival#Adjective is wrong for you?

**Comment by jmccrae** [comment]
Yeah, it is not something I would be happy to put in WordNet.

**Comment by vcvpaiva** [comment]
I disagree with @jmccrae. "Rival" in the sentence quoted 

>a prolonged dogfight over their rival bids for the contract

does look like an adjective to me, not the noun. it's more like "opposing bids, alternative bids". it has nothing to do with rivals like humans disputing something.

**Comment by restinplace** [comment]
"Rival" is pretty consistently defined (e.g. Oxford, Collins, Cambridge) as having noun and verb senses.   It is not entirely uncommon for English verbs to seem to be adjectives; see the discussion of verbal and deverbal adjectives here:
https://en.wikipedia.org/wiki/Attributive_verb 
"An attributive verb is a verb that modifies (expresses an attribute of) a noun in the manner of an attributive adjective, rather than express an independent idea as a predicate."

**Comment by leoalenc** [comment]
Both Cambridge and  Collins dictionaries register "rival" as an adjective:

https://dictionary.cambridge.org/pt/dicionario/ingles/rival

https://www.collinsdictionary.com/dictionary/english/rival

 I would like to suggest a simple test to  determine whether a word X that is a noun also functions as an adjective modifying a plural noun Y: if "X Y" can be converted to "the Y are X",  then X is an adjective. For example: "rival theories" can be converted to "the theories are rival", so "rival" is an adjective. The motivation for this test is the fact that adjectives in English don't inflect for number. If there were no "rival" adjective, then the conversion should be "the theories are rivals". There are many examples on Google of "rival" used as a predicative adjective, e.g.:

Experimental and Quasi-Experimental Designs for Research
Donald T. Campbell, Julian C. Stanley · 2015 · Psychology
... of frequently plausible hypotheses which are rival to the hypothesis that the experimental variable has had an effect.

Note that the test is formulated using unidirectional implication, so it has nothing to say about adjectives like "former" that are only used attributively.

**Comment by restinplace** [comment]
Re Cambridge/Collins, my error -- these sites appear to have multiple complete entries (for separate regional or subject editions?), separated by advertising.   I cited what appears to be the "main" entry; 
apologies for confusing the matter. 

Re  the test you propose, I think the question is not whether it's a noun that acts as an adjective, but whether it's a verb that acts as one.    

In this particular case, I would asterisk both of these as unacceptable to the (deep sigh ... ok, to this) educated native speaker or editor:  
*the theories are rival"   
 -- the theories are rivals    (the singular reads like a faux passive voice song lyric).
*hypotheses which are rival to the hypothesis that ... "
 -- hypotheses that rival the hypothesis that ...     (note also incorrect use of "which").

For example, the Corpus of Contemporary American English has only a single example of "are rival" used this way, i.e. in an awkward and incorrect passive construction:
 "assumes  that all services | are  rival | and thus underestimates the per capita value of nonrival ...."
The historical COHA corpus has none (https://www.english-corpora.org). It's not that the usage doesn't appear, but rather that when it does it is not acceptable (in my opinion).

**Comment by vcvpaiva** [comment]
I am confused

>I think the question is not whether it's a noun that acts as an adjective, but whether it's a verb that acts as one.

if the verb is acting as an adjective, isn't it an adjective?
 in the phrase "rival theories abound",  are you claiming that "rival" is a verb??!...

**Comment by jmccrae** [comment]
@leoalenc makes a good point about the use of 'rival' as an adjective in some phrase. My intuition and that of other native speakers I have talked to is that 'the theories are rival' is ungrammatical and it should be 'the theories are rivals', however it seems that a small minority of speakers do support this.

I examined Sketch Engine's enTenTen15 corpus for two phrases "are rivals to" and "are rival to", which clearly distinguish the part of speech, and found 26 usages of the noun form and only 4 of the adjective form.

As such, it seems that there is some support (among some speakers) for the use of rival as an adjective, although I suspect that this is relatively uncommon. Still it is probably worth adding an adjective sense of 'rival'. 

I would propose this as an additional member of this synset:

`ewn-01249022-s` (Interlingual Index: i6819)
(s) opposing, opponent 
> characterized by active hostility "opponent (or opposing) armies"

**Comment by restinplace** [comment]
> if the verb is acting as an adjective, isn't it an adjective?
No, because it only acts as an adjective in limited circumstances.

> in the phrase "rival theories abound", are you claiming that "rival" is a verb??!...
Yes -- an attributive verb:  
crazy theories abound
crazier theories abound
rival theories abound
*rivaler theories abound
Alice's poems rival Bob's songs.
Bob's songs are crazy.
*Alice's poems rival.
*Alice's poems are rival.
Alice and Bob write poems that rival Carol's songs ... 
*... but Alice's are rivaler ... 
* ... while Bob's are less rival.

One could argue that in "rival theory," "rival" is a noun adjunct or attributive noun
https://en.wikipedia.org/wiki/Noun_adjunct
rather than a attributive verb.  But in either case:
 - rival is readily shown to be a verb ("Alice rivals Bob") and a noun ("Bob is Alice's rival").
 - rival has no adjective properties that cannot be explained by the grammatical roles of attributive verb / noun (indeed, what is their function if not for cases like this?).
 - rival cannot fill other regular adjective slots.
 - "rival" means "compete / competing, providing an alternative" or "competitor / alternative," without any requirement for hostility:  "modern poets cannot rival the Greeks' use of rhyme," "there was no rival bid," "they were unwitting rivals." 

Re John's mention of the enTenTen15 corpus, the observation that "some speakers support" X, and the conclusion that "it is probably worth" accepting their judgment -- imho this is not a good path to go down.   For example, I find that "yeild" [sic] has 447 (noun), 225 (verb), and 8 (adj) entries.  This tells me only that the larger and less discriminating a corpus is, the more likely it is to provide support for unacceptable forms.

**Comment by vcvpaiva** [comment]
>One could argue that in "rival theory," "rival" is a noun adjunct or attributive noun

well, it seems that what you call a "noun adjunct" is what I learned to call a (half of a) "noun-noun compound". Then we have the problem that "rival" as a noun is classified as a person noun by PWN. 

But this argument I could see. What I did not understand was the suggestion that "rival" should be
an attributive verb.

**Comment by leoalenc** [comment]
Is this supposed attributive use of a verb a regular pattern in English?  I would like more examples to support this hypothesis. It seems strange to me from a syntactical point of view.  I think we should have the -ing form in this case, e.g. rivaling companies,  walking dead, etc. I'm not a native speaker,  but I am familiar with formal descriptions of English syntax. On the other hand, it is well known in the literature that not all adjectives can build comparative and superlative forms. I think this is the case with rival as an adjective.  This is possibly a case of dialectical variation.  On Google Books, one can find some examples of the construction "are rival to" occurring in more reliable sources that seem representative of some variant of standard English.

**Comment by leoalenc** [comment]
Interestingly, in the Wikipedia   article 

https://en.m.wikipedia.org/wiki/Attributive_verb

cited above, there is no example of attribute verb  formally similar to "rival bids".  Verb forms in this construction are typically non-finite forms in English, i.e. participles and to-infinitives.  The only examples mentioned with the plan infinitive are compounds, for example no-go area

**Comment by leoalenc** [comment]
Please correct the misspelling above: it should read dialectal variation

**Comment by restinplace** [comment]
>  I think we should have the -ing form in this case, e.g. rivaling companies, 

*rivaling companies (except as a verb, e.g. "partnerships rivaling companies for domination of ...").   I suppose you could say that "rival companies" is irregular, and exemplifies the zero -ing case ;)   

I think the central point is that both verbs and nouns may fill the grammatical roles of adjectives in some cases, and that in the specific instance of "rival," adding a verb sense to the existing noun sense can satisfy both the verb and (derived) adjective interpretations.  

I tend to think verb -> attributive verb (based on the definition "... a verb that modifies a noun in the manner of ...") because: 
 - "rival theory" can usually be replaced exactly by the verb-ish "competing theory," but is less likely to be intended to be synonymous with the noun-ish "alternative theory."  
 - a  more specific designation -- deverbal adjective -- usually involves a morphological change, as in "competing".

But it's not clear to me that there are always bright lines of derivation, or that they would be useful if there were.   For example, the English lyrics to "So Nice" (aka "Samba de Verão") include "summer samba (n)" and  "samba (v) through life."  

Is its third use --"sing to me some little samba song" -- derived from the noun or the verb?   Does it really matter?   Would it prompt a call for an adjective entry for "samba" in either case?

**Comment by jmccrae** [comment]
To close this issue. We already have 'rival' as a verb and from my understanding of the term 'attributive verb' this is something already covered by the way verbs are captured in WN.

As pointed out by @leoalenc, there are some uses of rival as an adjective and even though I personally wouldn't use the word in this way, there is corpus evidence. 

The proposed change is to add one new synset for 'rival' as an adjective and close this issue.

**Comment by jmccrae** [comment]
New synset.
Definition: as a rival in a competition
Derived from: `ewn-01124620-v`
