### ISSUE TITLE
Social roles

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#187]
Many social roles are hyponyms of the following synset.

`ewn-00007846-n` (Interlingual Index: i35562)
(n) individual, someone, somebody, mortal, soul, person 
> a human being "there was too much for one person to do"

However, many of these are not necessarily humans as proposed by the synsets, e.g, 'capitalist', 'coward', 'creator'...

As such I would propose a new synset for social role that could be used as the hypernym of these concepts *when the concept does not unequivocally refer to a human*. We would then move all social roles to be under this synset in the hierarchy.

**Comment by piekvossen** [comment]
This would solve part of the problem indeed.
Piek

On 27 Aug 2019, at 13:40, John McCrae <notifications@github.com<mailto:notifications@github.com>> wrote:


Many social roles are hyponyms of the following synset.

ewn-00007846-n (Interlingual Index: i35562)
(n) individual, someone, somebody, mortal, soul, person

a human being "there was too much for one person to do"

However, many of these are not necessarily humans as proposed by the synsets, e.g, 'capitalist', 'coward', 'creator'...

As such I would propose a new synset for social role that could be used as the hypernym of these concepts when the concept does not unequivocally refer to a human. We would then move all social roles to be under this synset in the hierarchy.

**Comment by arademaker** [comment]
Hi @piekvossen what is the rest of the problem? I understood that roles are difficult to model, see Fellbaum's comment in https://github.com/globalwordnet/english-wordnet/issues/5#issue-340700342 

What about using the hyperonym of individual 'causal_agent' as hyperonym of all cases that are not human being?

**Comment by piekvossen** [comment]
The problem is that these nouns behave like predicates with selectional restrictions that are defined proto and stereotypical. Different things can be an agent and this can change quickly (AI, forces, spirits, aliens). If we remove these from the "person" hypernym and link them to this abstract hypernym we loose information what our typical filler is for this role. To do this more properly, we need something more powerful than wordnet.

So maybe that is the solution:

1. link these to causal_agent 
2. combine Wordnet with something such as FrameNet or VerbNet to add selectional restrictions to fillers (which may be culturally defined, e.g. food applies to edible things which changes from culture to culture)

Note that there are other roles: patients, instruments, resources, etc...

**Comment by jmccrae** [comment]
I don't think this was every actually fixed. I am reopening.
