### ISSUE TITLE
Merge "serious-minded" and "sensible"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#39]
Highly similar definitions:

serious-minded, thoughtful `ewn-02127251-s`
> acting with or showing thought and good sense

sensible, reasonable `ewn-01950023-a`
> showing reason or sound judgment

**Comment by jmccrae** [comment]
Proposed new definition for `ewn-02127251-s`: 'characterized by solemn, sincere manner'

https://www.dictionary.com/browse/serious-minded?s=t
https://www.lexico.com/definition/serious-minded

Update examples of this synset

**Comment by arademaker** [comment]
@vcvpaiva can you give arguments for your negative vote?

**Comment by dcillessen** [comment]
> Proposed new definition for `ewn-02127251-s`: 'characterized by solemn, sincere manner'
> 
> https://www.dictionary.com/browse/serious-minded?s=t
> https://www.lexico.com/definition/serious-minded
> 
> Update examples of this synset

Are you suggesting that we leave the synsets separate and just update `ewn-02127251-s`?
This seems like the right move to me because there is a difference in emotional tone between "serious-minded" and "sensible," where "serious-minded" is more somber. 

As an example for `ewn-02127251-s` I'd suggest something like: "The serious-minded doctor carefully considered what to do next."
