### ISSUE TITLE
Merge "licensed" and "authorized"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#42]
Highly similar definitions:

commissioned, licensed, licenced, accredited `ewn-00180111-s`
> given official approval to act

authorized, authorised, authoritative `ewn-01636851-s`
> sanctioned by established authority

**Comment by jmccrae** [comment]
Issue #35 again

**Comment by arademaker** [comment]
We should merge them.

**Comment by dcillessen** [comment]
The difference between these synsets is where the definitions derive authority from, with ewn-00180111-s "licensed" deriving it from an "office" and ewn-01636851-s deriving it from an "authority" in their definitions. 

This understanding, however, isn't backed up by the way these synsets are placed within the network. ewn-01636851-s "authorized" is related with ewn-01636580-a "official" (as "similar to") while ewn-00180111-s "licensed" is related with ewn-00179875-a "authorized" (as "similar to").

In my mind we should restructure the relations surrounding these synsets to support their definitions rather than merging them. (Perhaps by relating ewn-01636851-s with  ewn-00179875-a and ewn-00180111-s with ewn-01636580-a.) I'm open to being wrong here though because doing what I'm proposing might have ramifications on higher levels of the hierarchy or lead to higher level inconsistency.

**Comment by Ciara97olo** [comment]
I agree that the relations should be changed to support the definitions and the synsets should not be merged.
