### ISSUE TITLE
Incorrect derivation links

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#431]
There are some links between senses that are not true derivations

```
aggressive%5:00:00:hostile:01 to pugnacity%1:07:00::
sharp%5:00:00:pointed:00 to keenness%1:07:00::
ostentatious%5:00:00:tasteless:02 to splashiness%1:07:00::
clear%5:00:00:legible:00 to limpidity%1:07:01::
inconsiderate%5:00:00:thoughtless:00 to thoughtlessness%1:07:01::
diligent%5:00:00:patient:00 to industry%1:07:00::
tidy%5:00:00:groomed:00 to neatness%1:07:00::
inappropriate%5:00:00:incongruous:00 to wrongness%1:07:02::
stubborn%5:00:00:intractable:00 to mulishness%1:07:00::
bright%5:00:00:polished:00 to luminousness%1:07:00::
bad%5:00:00:intense:00 to severeness%1:07:03::
large%5:00:00:significant:00 to extensiveness%1:07:00::
serviceable%5:00:00:useful:00 to useableness%1:07:00::
indispensable%5:00:00:necessary:00 to vitalness%1:07:01::
purposeless%5:00:00:worthless:00 to aimlessness%1:07:00::
maxillary%3:01:00:: to maxillary%1:08:00::
comprehensive%5:00:00:inclusive:00 to largeness%1:09:00::
sour%5:00:00:tasty:00 to tartness%1:09:00::
cheerful%5:00:00:optimistic:00 to blitheness%1:12:00::
important%5:00:00:influential:00 to grandness%1:26:00::
anonymous%5:00:00:faceless:00 to namelessness%1:26:00::
neutering%1:04:00:: to castrate%2:29:02::
barrage%1:10:00:: to bombard%2:32:00::
```

Thanks to @ekaf for reporting.

**Comment by ekaf** [comment]
Changing the relationship to domain_topic seems like a good solution, since pertainyms never have been clearly defined. Maybe a similar treatment could apply to more of the incorrect derivation links?

It is a difficult problem since it relates to two questions which have been discussed intensely on the Princeton WordNet mail list without a convincing outcome: in 2018, I noted that 2296 PWN 3.1 derivations were also pertainyms, and in 2020, Finn Nielsen noted that the definition of pertainymy was not sufficiently clear. Christiane Fellbaum participated in both cases, but I am not yet convinced that there is a consensus.

**Comment by jmccrae** [comment]
I think it is best to create a new issue about pertainyms. IMHO they should be links from adjectives to nouns and adverbs to adjectives only, and only when the adjective is derived from the noun (and honestly I would use another name for adjective/adverb derivations).

**Comment by ekaf** [comment]
Yes, it would be better to use another name than pertainymy for adjective/adverb derivations, and maybe even also for the adjective/noun links.
Pertainymy expresses a morphological derivation, often from the Latin root instead of the English one, for ex. (dental, tooth). So "aggressive" is not a pertainym of "pugnacity" ('A natural disposition to be hostile'), and this also applies to the other incorrect derivations. It seems possible to see some semantic relationship between the involved words, but there may be no appropriate Wordnet label to encode that relationship.
Then it is fine to just delete these links, as #737 does.
