### ISSUE TITLE
Merge "abloom" and "flowering"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#44]
Highly similar definitions:

abloom, efflorescent `ewn-01492219-s`
> bursting into flower

flowering `ewn-02608165-a`
> having a flower or bloom

**Comment by vcvpaiva** [comment]
similar to issue #41, abloom is rarely used, while flowering is very used. I am against merging the synsets.

**Comment by jmccrae** [comment]
Frequency of usage is not a reason to distinguish synsets.

"flowering" certainly means "bursting into flower", "abloom" certainly means "having a flower or bloom" so both synsets should contain both words.

I can't discern a difference between the two definitions and the links in the graph do not give any reason to distinguish these synsets.

**Comment by arademaker** [comment]
I agree with @jmccrae, maybe @vcvpaiva have more arguments to keep these two synsets? 

> The building block of WordNet is a synonym set, or synset, consisting of all the words that can be substituted for one another in given types of sentential contexts without change of truth value in the sentences involved. Not all the members of a given synset will be interchangeable in all contexts.

**Comment by jmccrae** [comment]
Pushing to 2021 as there still seems to be disagreement

**Comment by dcillessen** [comment]
Currently the definitions point to slightly different meanings in my mind. 

"Abloom" refers to the act of bursting into a flower, hence its relationship to "efflorescent" which relates more broadly to different kinds of bursting forth. "Abloom" also here points towards the process of "bursting." 

The definition of "flowering" on the other hand describes the static state of something which possesses flowers.

A cherry tree may be described as "flowering" because it has flowers.  That tree is also "abloom" in the sense that its buds are "abloom," or are bursting into flower. 

Looking towards the etymology of "abloom" holds some answers in that it relies on [this](https://oed.com/view/Entry/270754#eid125019030) verison of the "a-" prefix, described as: 
> With nouns and verb stems, forming adverbs (and derived adjectives and prepositions) expressing activity, position, condition, etc. Now chiefly poetic. (OED def. 2)

In terms of WN relations, the distinction I am talking about is the reason that "abloom" (ewn-01492219-s) is related to "blossoming" (ewn-13460743-n, defined as "the time and process of budding and unfolding of blossoms").  "Flowering" (ewn-02608165-a) on the other hand is related to an antonym "flowerless" (ewn-02608266-a) which describes a state of being without flower or blooms.

So, ultimately, I think that the synsets should be kept unmerged.  My background is in literature though so I can see the case that these synsets are close enough in common usage to be merged. My argument hinges on a "chiefly poetic" prefix, after all.
