### ISSUE TITLE
Merge ewn-08269388-n "function" and ewn-07461861-n "affair, function, ..."?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#517]
I wonder if `ewn-08269388-n` "function" should be merged with `ewn-07461861-n`. The main difference is that they are assigned to different subjects. 

ID | Lemmas | Definition | subject 
-- | -- | -- | --
ewn-07461861-n | affair, function, occasion, social function, social occasion | a vaguely specified social event | noun.event
ewn-08269388-n | function | a formal or official social gathering or ceremony | noun.group

If we decide to merge both concepts I would prefer to keep the definition of `ewn-08269388-n` since the definition of  ewn-07461861-n is "vaguely specified" indeed. For comparison, here are some definitions from Wiktionary.

> affair:   8. A party or social gathering, especially of a formal nature.      
> function: 3. An official or social occasion.     
> occasion: 8. A special event or function.

The following table shows the transitive hypernyms of both concepts. `ewn-08269388-n` "function" does not have any other concept relations, so merging should not be a problem. 

Lemmas | Definition | affair,   function, [...] | function
-- | -- | -- | --
entity | that which is perceived or known or inferred to have its own distinct   existence (living or nonliving) | 1 | 1
abstract entity, abstraction | a general concept formed by extracting common features from specific   examples | 1 | 1
event | something that happens at a given place and time | 1 | 1
group, grouping | any number of entities (members) considered as a unit |   | 1
social event | an event characteristic of persons forming groups | 1 |  
social group | people sharing some social relation |   | 1
assemblage, gathering | a group of persons together in one place |   | 1
social affair, social gathering | a gathering for the purpose of promoting fellowship |   | 1

**Comment by rwingerter55** [comment]
I realize now that a merge is not necessary, we can just drop concept  `ewn-08269388-n` and its lexical sense.

**Comment by jmccrae** [comment]
A lot of this hierarchy seems to be odd and does not connect words that we would expect to be closely. I think the problematic synset here is really:

`ewn-07991473-n` (Interlingual Index: i79220)
(n) gathering, assemblage 
> a group of persons together in one place

This synset needs to be made clearer that it refers only to a group of people, and many of its hyponyms such as 'fair', 'wine-tasting', 'rave-up' and of course 'social gathering' should be moved elsewhere. 

I think there is a big issue with systematic polysemy as many of the hyponyms of `ewn-07991473-n` are words such as 'building', 'floor', 'municipality' used to refer to the people found at that place, which is clarified in the examples, e.g., "the _floor_ complained...". In this case, we could keep `ewn-08269388-n` but clarify that it refers to the people at a function rather than the function itself, although I think I would prefer the option of merging the synsets in the issue title and cleaning up `ewn-07991473-n`

**Comment by rwingerter55** [comment]
> A lot of this hierarchy seems to be odd and does not connect words that we would expect to be closely

> [... ] I think there is a big issue with systematic polysemy as many of the hyponyms of ewn-07991473-n are words such as 'building', 'floor', 'municipality' used to refer to the people found at that place, which is clarified in the examples, e.g., "the floor complained...". 

I agree completely. See new issue #518.
