### ISSUE TITLE
Hyponyms of ewn-07991473-n "gathering, assemblage"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#522]
#517 is tagged 'help wanted'. @jmccrae wrote:

> A lot of this hierarchy seems to be odd and does not connect words that we would expect to be closely. I think the problematic synset here is really:
> 
> `ewn-07991473-n` (Interlingual Index: i79220)
> (n) gathering, assemblage
> 
> > a group of persons together in one place
> 
> This synset needs to be made clearer that it refers only to a group of people, and many of its hyponyms such as 'fair', 'wine-tasting', 'rave-up' and of course 'social gathering' should be moved elsewhere.
> 
> I think there is a big issue with systematic polysemy as many of the hyponyms of `ewn-07991473-n` are words such as 'building', 'floor', 'municipality' used to refer to the people found at that place, which is clarified in the examples, e.g., "the _floor_ complained...".

I have selected all transitive hyponyms of `ewn-07991473-n`, their definitions and associated lexical entries plus all senses of these lexical entries. The result is 390 lexical entries, 905 senses and 710 concepts. I also looked up these lexical entries in [dbnary](http://kaiko.getalp.org/about-dbnary/) ("Wiktionary as Linguistic Linked Open Data"). I put everything into an Excel file as an attachment to this message. 

Next I will analyze what is there and try to propose changes, e.g. 

- Which hyponyms should be moved elsewhere?

- Where should they be moved?

- Identify cases of polysemy where important senses are missing.

If you want to help you are welcome!

[Hyponyms of gathering and assemblage v3a.xlsx](https://github.com/globalwordnet/english-wordnet/files/4920030/Hyponyms.of.gathering.and.assemblage.v3a.xlsx)

**Comment by rwingerter55** [comment]
### Where should the hyponyms be moved? 

`ewn-07991473-n` has `ewn-01232427-n` as a complement. The first designates a **group**, the second an **act** (cf. column subject). 

ID | Lemmas | subject | definition | example
-- | -- | -- | -- | --
ewn-07991473-n | assemblage, gathering | group | a group of persons together in one   place | (none)
ewn-01232427-n | assembly, assemblage,   gathering | act | the social act of   assembling | "they demanded   the right of assembly"

Polysemic hyponyms of `ewn-07991473-n` that don't fit in where they are because they designate an act or activity rather than a group could become hyponyms of `ewn-01232427-n`.

**Comment by rwingerter55** [comment]
![image](https://user-images.githubusercontent.com/62653433/87851577-5adc7d00-c8fa-11ea-81eb-a53ddf9d0e4a.png)

Screenshot from https://visuwords.com/social%20affair. The site is based on Princeton WordNet.

**Comment by rwingerter55** [comment]
Here is a visualization copied from [visuwords.com](https://visuwords.com/gathering). It shows that the "assemblage, gathering" has more hyponyms than "assembly, assemblage, gathering".

![image](https://user-images.githubusercontent.com/62653433/87855433-9f771100-c918-11ea-8e21-c728c7facf36.png)

**Comment by rwingerter55** [comment]
I think `ewn-07461861-n` "social occassion, ..." would be a more appropriate place. 

![image](https://user-images.githubusercontent.com/62653433/87855779-c6cedd80-c91a-11ea-8f8a-928e47952b31.png)

**Comment by ekaf** [comment]
@rwinger proposes that the synsets "'fair', 'wine-tasting','rave-up' and of course 'social gathering'" should be hyponyms of the "noun.act" sense of "gathering", instead of its "noun.group" sense.

I agree for 'fair', 'wine_tasting', and 'social gathering', but am not sure about 'rave-up', because it can mean a group.

The gloss of 'party' (a hyponym of 'social gathering') would also need to be modified to mean an "act", rather than 'A group of people gathered together for pleasure'.

Additionally, the following two could also be moved to 'noun.act':
> rally, mass meeting (hypernym of revival, pep_rally)
> meeting, group meeting (A formally arranged gathering)

But the real problem may be how to make the proposed edit in practice: I have used EWE to delete the existing hyponymy relation between "social gathering" and the "group" sense of "gathering", and then add a hyponymy relation to the "act" sense instead. It works, but it doesn't move "social gathering" and its many hyponyms into the wn-noun.act.xml file, as would be desirable.

**Comment by rwingerter55** [comment]
> I agree for 'fair', 'wine_tasting', and 'social gathering', but am not sure about 'rave-up', because it can mean a group.

@ekaf, according to #680 a new sense/synset `ewn-87903366-n` has been created for 'rave-up'.
