### ISSUE TITLE
Social distancing

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#545]
Add a new synset for this term

**Comment by ekaf** [comment]
There is some controversy: I have heard the argument that what is actually meant is "physical distancing", which indeed seems more proper. Maybe add both as synonyms, since both are widely used.

**Comment by ekaf** [comment]
Are there two senses of "social distancing"?

"Social contact" is not yet in WordNet. However, it would probably not be considered a synonym of "physical contact", but rather a broader form of contact, which would include different particular modes of contact as hyponyms, with "physical contact" among these. By analogy then, "physical distancing" could be a hyponym of "social distancing". However, both are currently widely used as synonyms. This narrow sense of "social distancing" may be considered a misnomer but, currently, it is the only way that this expression is actually used.

Logically, there would be a case for also expecting the existence of a broader, more proper sense of "social distancing", which could f. ex. mean "keeping a social distance from other people, f. ex. in online social networks". Maybe such a hypothetical sense distinction could have been deemed worthwile to have in PWN. But it does not seem fit for inclusion in EWN, since this broader sense of "social distancing" doesn't currently have any actual use.

**Comment by jmccrae** [comment]
I think the second case would need to be well-attested in source material and I think it would be hard to find sufficient examples to support this. The pull request looks good, so I am happy to merge and close this issue, if you are satisfied?

**Comment by ekaf** [comment]
Could we think over it just a little bit more? Actually, in the scientific literature, there is support for a broader sense of "social distancing" that goes beyond the strict distance between individuals, and also encompasses distancing between groups:

"Social distancing can reduce virus transmission by increasing physical distance or reducing frequency of congregation in socially dense community settings, such as schools or workplaces."
(Ahmed et al., Effectiveness of workplace social distancing measures in reducing influenza transmission: a systematic review, BMC Public Health (2018) 18:518, https://doi.org/10.1186/s12889-018-5446-1)

The following seems to also relate to the same broader sense:

"Between these responses, many countries are adopting measures termed "social distancing" or "physical distancing," closing schools and workplaces and limiting the sizes of gatherings."
(Stephen Kissler et al., Social distancing strategies for curbing the COVID-19 epidemic, 2020, https://doi.org/10.1101/2020.03.22.20041079)

But there is also third, completely diffent sense, stemming from anthropology:

"Social distancing is a relatively informal kind of social control. [...] As described in these literatures, social distancing is a kind of informal ostracism that occurs in response to social deviance by individual members or minority subgroups of a larger group or society."
(Westphal and Khanna, Keeping Directors in Line: Social Distancing as a Control Mechanism in the Corporate Elite, 2003)

What do you think? Maybe these senses are a little bit too specialized. But this was the kind of fine-grained coverage that was so apreciable in PWN.

**Comment by ekaf** [comment]
The definition in the PR has been broadened, to include more of the "social" aspect. I think that this is a reasonable, "middle of the road" solution, that avoids sense proliferation, while covering relevant details. 
The more specialized anthropological sense is less vital and can wait for another eventual PR.
