### ISSUE TITLE
Merge "collect" and "gather"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#55]
Highly similar definitions:

collect, pull in `ewn-01387093-v`
> get or bring together

amass, cumulate, accumulate, conglomerate, pile up, gather `ewn-00158612-v`
> collect or gather

**Comment by restinplace** [comment]
These items illustrate a more complex problem.  This example shows 
disjoint lexemes / synsets that cover the same semantic field.  However, 
they can't be separated from the problem of  clarifying disjoint senses 
(for "collect", in particular) whose definitions may not adequately distinguish them.  

My point is that 
 a) examples like the above can't be correctly solved pair-wise, and 
 b) imho the underlying problem of distinguishing (and very rarely 
    merging) senses of relatively common lexemes and synsets is both 
    more important for WN use, and is a necessary preliminary for good 
    cross-lexeme / cross-synset work.

Semi-disclaimer:  I'm still reading through all open and closed issues to 
try to get the big picture -- this is just a passing comment rather than a 
proposal for a new procedure.

**Comment by jmccrae** [comment]
This seems to be a definition issue more than actual duplicates. New defintion of `ewn-00158612-v` should be "increase in amount by collecting or gathering"
