### ISSUE TITLE
ewn-00358508-v bourgeon - new examples required

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#744]
**Synset**
> ewn-00358508-v burgeon

**Example**
> The burgeoning administration" "The burgeoning population"
Change examples - New examples required. 

Some examples I found on the web:

- A militant party bourgeons in India
- As spring burgeons, so do local activities
- Baby chick burgeons in five weeks to a full-size bird

**Motivation**
Examples use adjective 'burgeoning' (which does not exist in EWN).

**Comment by jmccrae** [comment]
I guess the real issue is that "burgeoning" is not an adjective, but the word is nearly only used as an adjective in modern usage.
A solution may be to add 'burgeoning' to the synset for 'flourishing' as well:

https://en-word.net/lemma/flourishing

The examples of 'burgeoning' could be added to this synset, and the example of 'burgeon' as a verb used only for this synset.

Do you agree @EnejdaN and @rwingerter55?
