### ISSUE TITLE
2021 Release Candidate

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#747]
All issues are now closed and the 2021 candidate is ready to be released. 

I have the candidate files here:

* GWA XML: http://john.mccr.ae/oewn2021/english-wordnet-2021.xml
* RDF: http://john.mccr.ae/oewn2021/english-wordnet-2021.ttl.gz
* WNDB: http://john.mccr.ae/oewn2021/english-wordnet-2021.zip

Please let me know if there are any issues

**Comment by rwingerter55** [comment]
The RDF version works for me. I could owl:import it into VocBench 3 (with GraphDB Free as backend and with RDF4J) without a problem and so far everything looks fine. One very minor thing: the wn ontology (https://globalwordnet.github.io/schemas/wn#) had to be owl:imported separately (I could not find an owl:imports statement in the turtle file).

**Comment by ekaf** [comment]
WNDB is useless because index.sense contains 0 bytes. Many further tests require the sense keys.
Also no frames (+) are present in data.verb.

**Comment by rwingerter55** [comment]
The RDF version includes examples. FWIW, here are the statistics. 

partOfSpeech | noOfSynsets | withExamples | pct
-- | -- | -- | --
adjective | 10726 | 7588 | 71%
adjective_satellite | 16329 | 12569 | 77%
adverb | 4609 | 4169 | 90%
noun | 87119 | 12776 | 15%
verb | 16696 | 12546 | 75%
**Total** | **135479** | **49648** | **37%**



</body>

</html>

**Comment by jmccrae** [comment]
Thanks, I have updated the candidates:
* OWL:imports statements added
* Sense IDs no longer contain `:`
* `index.sense` is not empty
* Frames are available in the verb sections of the WNDB export

**Comment by ekaf** [comment]
In the GWA XML file, the new Sense id format is unpractical to parse because underscore is overloaded as both a key separator and a space in multi-word expressions: for ex. id="ewn-a_la_carte__3_00_00__".

XML Relation statistics:
    3878 also
    8000 antonym
    1278 attribute
     221 causes
   74687 derivation
    1511 domain_region
    6730 domain_topic
     408 entails
    1379 exemplifies
    1511 has_domain_region
    6730 has_domain_topic
   12291 holo_member
    9199 holo_part
     830 holo_substance
   91503 hypernym
   91503 hyponym
    8589 instance_hypernym
    8589 instance_hyponym
     221 is_caused_by
     408 is_entailed_by
    1379 is_exemplified_by
   12291 mero_member
    9199 mero_part
     830 mero_substance
       4 other
      73 participle
    8073 pertainym
   23194 similar
  384509 total

**Comment by jmccrae** [comment]
@ekaf sense keys are parsed and verified at every commit. The actual implementation is here:
https://github.com/globalwordnet/english-wordnet/blob/master/scripts/wordnet_yaml.py#L21

**Comment by ekaf** [comment]
In the second WNDB export, index.sense is not in the proper PWN format, because the sense keys use __ instead of the specified %.
Also, all synsets in the data.* files still have lex_filenum 45  (which is not a valid number) instead of their correct lex_filenum.

**Comment by ekaf** [comment]
Concerning the new XML Sense id format, I still find it unpractical to extract the individual components of an id like "ewn-a_la_carte__3_00_00__", where there is no fixed number of components, since underscore is used both inside and outside lemmas, and __ may appear once or twice.

**Comment by jmccrae** [comment]
The ID format change was proposed a few months ago in #662. It was then pointed out in #749 that using `:` in XML IDs breaks some systems. 

Another option could be to use periods, e.g., `ewn-a_la_carte__3.00.00..`

**Comment by ekaf** [comment]
Yes,any separator that is different from the word space would be fine.

**Comment by ekaf** [comment]
After applying small hacks, the WNDB works with NLTK. First, NLTK complains that the 'lexnames' file is absent. After copying this file from any previous release (it never changed since WN 1.6, where it was introduced), an error is raised because 45 is not a valid lexfile number. After adding 45 in 'lexnames', everything went smoothly. Of course, index.sense was fixed to conform to the PWN sense key format.
 
After this I used the new graph capabilities of the current development branch in NLTK to draw the hyponyms of meeting:

> import nltk
> from nltk.parse.dependencygraph import dot2img
> from nltk.corpus import wordnet as wn
> dot2img(wn.digraph([wn.synset('meeting.n.01')], lambda s:s.hyponyms(), attr={'rankdir':'LR', 'compound':'true'}, shapes={'':'plaintext'}), 'png')
![hypo-meeting](https://user-images.githubusercontent.com/4782556/132829023-be38eb7f-240d-43e1-a4d1-f253c5432472.png)

**Comment by 1313ou** [comment]
Not really "a few months ago" but July 15, 
"The IDs we use on sense's XML **will be changed** to resemble the PWN sense IDs"
No idea then what they would look like. The introduction of colons was not announced.

**Comment by ekaf** [comment]
Maybe reopen #662, so that the issue can be discussed? The introduction of underscores was even less announced than the colons.

**Comment by jmccrae** [comment]
I have reopened, but I hope that the use of periods is the most acceptable solution and that we can close this quickly to proceed with the release.

**Comment by 1313ou** [comment]
Wouldn't it have been simpler to keep the previous **ID** and also preserve the sense key as it was (parseable, with colons as fields), a simple (legacy) **key** that doesn't have to bear the xsd:ID requirements. 
I don't understand the point of this move. We're not pressed for space, the word net is not going to be stored in a microcontroller, where resources are scarce.

**Comment by ekaf** [comment]
As proposed by @1313ou, keeping the original verbatim sense keys would be ideal, if feasible

**Comment by jmccrae** [comment]
The reason for change was a bug report by @1313ou

https://github.com/globalwordnet/schemas/issues/5 and https://github.com/globalwordnet/schemas/issues/25

Please note that we also intend to drop the XML as a working format (see #664) and the YAML version has no issues with using the Princeton sense keys as is. Please also note that the previous XML ID scheme is highly problematic to calculate and involves lots of 'encoded' information. I am happy to reintroduce the verbatim sense keys as another attribute but it seems pointless when they can easily be obtained from the IDs.

**Comment by 1313ou** [comment]
> Please also note that the previous XML ID scheme is highly problematic to calculate and involves lots of 'encoded' information.

Can you elaborate on that ? If it was used for the 2020 release, why shouldn't it work now?

globalwordnet/schemas#5 was not in favour of using sensekeys as IDs, it was intended to clarify their status as inner (generated) **keys** or foreign legacy **keys** (referring to PWN)

**Comment by jmccrae** [comment]
The old sense IDs encoded the ordering of members of a synset. This is now captured by the `members` attribute on synsets. It was a horrible hack that caused lots of headaches!

**Comment by 1313ou** [comment]
So now that the ordering is readily available, I take it it should be easy to use it when generating IDs.

**Comment by jmccrae** [comment]
I updated the Release Candidate (WNDB Export)

* Added `lexnames`
* Fixed lexfiles in `data.noun` (etc). There is no more lexfile number 45!
* Fixed IDs in `index.sense`

**Comment by jmccrae** [comment]
> So now that the ordering is readily available, I take it it should be easy to use it when generating IDs.
Yeah... sort of... but it is easier to remove the hack entirely. Part of the issue is that incoming links would get broken by rearrangements of the order of members in the synset as this changed the sense IDs that were used as targets.

**Comment by goodmami** [comment]
I tried loading the XML file with Wn but got this:

```pycon
>>> import wn
>>> wn.add('english-wordnet-2021.xml')
Skipping ewn:2020 (Open English WordNet); already added

>>> 
```

This is because the `version` attribute on `<Lexicon>` is still "2020". I understand not wanting to version it "2021" until it's ready, but it's also inaccurate to say "2020". What about "2021rc1", etc. for pre-release versions?

**Comment by ekaf** [comment]
In wndb, everything is ok now: there are no ambiguous sense keys, no transitive loop, every symmetric relation is symmetric, and the asymmetric ones are as expected.

There is only one minor annoyance left in data.noun: the gloss at offset 15539647 has a few spurious backslashes:  "We, the intellectually curious, may soon find ourselves trapped in a pen,\ \ fenced in by rule-bound sticklerism and overzealous concern for our personal\ \ safety, unless we exercise our civil liberties and our curiosity," he declaims.

**Comment by ekaf** [comment]
@jmccrae wrote "I am happy to reintroduce the verbatim sense keys as another attribute but it seems pointless when they can easily be obtained from the IDs."

Yes, if sense keys can be obtained from the IDs by a simple translation of the separators, i. e. without looking up in an extensive mapping, then there is no need to have two different attributes for the same information.

**Comment by jmccrae** [comment]
Updates on Release Candidates

* Updated definition of 'sticklerism' (all versions)
* Sense IDs use periods (XML) cf #754 
* `version=2021` (XML)

**Comment by goodmami** [comment]
@jmccrae thanks, the XML version loads without issue, now.

Sorry I'm a bit late to the discussion on XML IDs. I don't want to delay things, but I'm concerned about the method of replacement for punctuation, as noted in globalwordnet/schemas#55. Specifically the use of dashes both to delimit escape sequences and as literal dash characters makes it ripe for collisions. Here's an example with both:

```xml
<LexicalEntry id="ewn-bird-ap-s-eye-s">
```

The relevant code is here:

https://github.com/globalwordnet/english-wordnet/blob/82b710381477e4a0c5766f53c468029727b9b6f8/scripts/wordnet.py#L774-L775

I don't think there's any issues now, but considering that, for example, `!` becomes `-ex-` and some words have *ex-* (e.g., *ex-president*), it's not a stretch to imagine we might have *ex-ex-* (e.g., *ex-ex-president*). Since these issues are only with XML IDs and not specific to English, I propose that we have a lossless XML-ID sanitation function for all WN-LMF wordnets (not just OEWN). By "lossless" I really mean collision-free, as I don't think IDs should be parsed and interpreted, but it could be nice to recover the original ID.

**Comment by jmccrae** [comment]
Yeah, there is a risk of collisions, but we verify all IDs for uniqueness as part of the post-commit validation and we can change the scheme at future points if we wish. As such, I think it is okay to keep with the current scheme.

**Comment by goodmami** [comment]
Fair enough. From my point of view as a library developer who wants to [support lookup by sense key](https://github.com/goodmami/wn/issues/55), however, this means I may need to develop a custom function each time the ID-transformation scheme changes. Maybe by the next release we can find something more robust and permanent.

**Comment by ekaf** [comment]
WNDB index.sense is still not conformant, because all the sense keys except adjective satellites should have trailing "::", but miss it. For ex. "accommodate%2:30:00" should be "accommodate%2:30:00::".

**Comment by jmccrae** [comment]
> WNDB index.sense is still not conformant, because all the sense keys except adjective satellites should have trailing "::", but miss it. For ex. "accommodate%2:30:00" should be "accommodate%2:30:00::".

Thanks, updated!

**Comment by ekaf** [comment]
When lemmas include periods, as in ewn-d.p.r.k.__1.15.00.. (ewn-08974855-n), the simple translation of the new ID separator to colon is unpractical. I am trying to verify if the new Sense Ids really translate to sense keys. It works except in 594 cases, where 590 concern periods.

**Comment by 1313ou** [comment]
It's definitely safer to keep the verbatim sensekey as a separate key and consider the new ID as opaque (unparseable, what it should be in the first place), constrained only by 1) xsd:ID well-formedness, 2) uniqueness and 3/ proper reference. This leaves us some leeway to make it evolve.

**Comment by ekaf** [comment]
All 211865 Sense Ids from the XML db translate to the 211865 sense keys in index.sense. 

Four cases have -sp- replaced by an underscore, and 590 lemmas include periods. In that case, the following sed command can be used on Sense Ids, to translate only the periods after the double underscore to colons:
> sed -e :1 -e 's/\(__.*\)\./\1:/;t1'

Maybe it would be simpler to have an expression like -pe- to express periods.

**Comment by ekaf** [comment]
Since Sense Ids and Sense Keys translate to each other, the WN 3.1 synset offsets used in the XML file can easily be mapped to the WNDB offsets. As expected, this is a one-to-one mapping, with no splits or merges, since both columns relate to the same release.
Comparing  the 120039 synset offsets from the XML file, with the 117791 original PWN 3.1 synset offsets, gives a quite plausible result, since 117715 are identical, while only 76 have been removed and 2324 added.

**Comment by ekaf** [comment]
2598 synsets have the same ili 'in', f. ex. 13883813-n.

**Comment by jmccrae** [comment]
> 2598 synsets have the same ili 'in', f. ex. 13883813-n.
This is correct. `in` means that they are new synsets which have not had a code proposed yet

**Comment by ekaf** [comment]
@jmccrae When and how do these synsets get an ILI? It would be best if it happens before the release.

**Comment by fcbond** [comment]
It would be good to change the prefix to match the label: 'oewn', see #759.

**Comment by fcbond** [comment]
> @jmccrae When and how do these synsets get an ILI? It would be best if it happens before the release.

In the current workflow (which is not yet working as designed), a new ILI is only assigned after a wordnet has been released, as there has to be some commitment to it being necessary.    So the release should happen, then ILI's get assigned.

**Comment by 1313ou** [comment]
All clear for me, all the way down to WNDB, SQL and phone apps.

![Screenshot_2021-10-09-17-54-29-473_org treebolic wordnet browser](https://user-images.githubusercontent.com/16848556/136666261-ed79f5aa-7bdc-4d65-9efa-62c5299c2561.jpg)
![Screenshot_2021-10-09-17-59-04-305_org sqlunet browser ewn](https://user-images.githubusercontent.com/16848556/136666263-9a548bb1-c2ed-486b-b916-a9ede8660993.jpg)

**Comment by jmccrae** [comment]
Updated versions released at https://en-word.net

I will announce the release tomorrow

**Comment by ekaf** [comment]
A small number of WNDB data.* synsets have definitions with more than one "|", leading to parse failures.
> awk -F"|" 'NF>2' data.*

02020442 00 a 01 rural 0 011 ! 02022522 a 0101 + 04961506 n 0102 & 02020981 a 0000 & 02021158 a 0000 & 02021320 a 0000 & 02021613 a 0000 & 02021727 a 0000 & 02021895 a 0000 & 02022057 a 0000 & 02022225 a 0000 & 02022388 a 0000 | of or relating to the countryside as opposed to the city; living in or characteristic of farming or country life| living in or characteristic of farming or country life; rural people; large rural households; unpaved rural roads; an economy that is basically rural; rural electrification; rural free delivery  
00511460 02 r 07 suddenly 1 all_of_a_sudden 1 on_the_spur_of_the_moment 1 of_a_sudden 1 abruptly 1 dead 1 short 8 002 \ 01125863 a 0101 \ 00511460 r 0505 | quickly and without warning| happening unexpectedly| on impulse; without premeditation; he stopped suddenly; suddenly she felt a sharp pain in her side; he decided to go to Chicago on the spur of the moment; he made up his mind suddenly  
07801774 13 n 0a moong 0 green_gram 0 monggo 0 green_bean 1 munggo 0 mung 0 mash_bean 0 mung_bean 0 green_soy 0 golden_gram 0 002 @ 07801444 n 0000 #p 12683521 n 0000 | seed of the mung bean plant used for food| food from the seed of the mung bean plant  
12683921 20 n 0a moong 0 green_gram 0 monggo 0 green_bean 1 munggo 0 mung 1 mash_bean 0 mung_bean 1 green_soy 0 golden_gram 0 002 @ 13245376 n 0000 #p 12683521 n 0000 | seed of the mung bean plant; used for food| seed of the mung bean plant  
02763303 32 v 01 tweet 1 002 @ 00987481 v 0000 @ 01065604 v 0000 02 + 02 00 + 08 00 | To post a message on Twitter| post tweets, i.e. short text messages on the popular social media website Twitter  

These explain all the 23 key errors which do not concern adjective satellites.

**Comment by jmccrae** [comment]
I updated the WNDB files again. @ekaf I can't seem to reproduce these errors. Perhaps you could share with me the code that you are testing?

**Comment by ekaf** [comment]
Of course @jmccrae, here is the code. But to support PWN 3.1, it requires the latest NLTK  'develop' branch, plus the latest nltk_data, and additionally you need to copy the EWN 2021 wndb files to a directory called wordnet2021 under nltk_data/corpora, and uncomment the line that mentions 'wordnet2021' in nltk/corpus/__init__py, because NLTK does not yet support EWN .

```
import nltk
from nltk.corpus import wordnet31 as wn1
from nltk.corpus import wordnet2021 as wn2

v1=wn1.get_version()
v2=wn2.get_version()

keys1={l.split()[0].lower() for l in wn1.open('index.sense')}
keys2={l.split()[0].lower() for l in wn2.open('index.sense')}

for sk in keys1.intersection(keys2):
    try:
        lem=wn2.lemma_from_key(sk)
    except:
        lem1=wn1.lemma_from_key(sk)
        print("Bad key in Wn {}: {} (Wn {}:{})".format(v2,sk,v1,lem1))

```

**Comment by ekaf** [comment]
Congratulation @jmccrae, there are no more bad keys in the newest WNDB update, after the ordering of words within their synsets is fixed.
The stability of the NLTK synset identifiers for EWN 2021 w.r.t. PWN 3.1 is much improved, compared to https://github.com/globalwordnet/english-wordnet/issues/747#issuecomment-950528484, although it could still be better, since the ordering of synsets for each lemma in the index.POS* files has changed more than it probably needs to.
Here are extracts from the output of the attached test script [synchanged.py.txt](https://github.com/globalwordnet/english-wordnet/files/7459290/synchanged.py.txt):

15 (0.01%) lemmas from Wn 3.1 changed in Wn 2021
These are mostly changes in capitalization, for ex.:
```
Key baroque%3:01:00::
    Wn 3.1: Lemma('baroque.a.02.baroque')
    Wn 2021: Lemma('baroque.a.02.Baroque')

```

2124 (1.8%) Synset id. wordnames from Wn 3.1 changed in Wn 2021
These are mostly proper names, with the long form now being preferred over the short form, for ex.:
```
Key lexington%1:04:00::
    Wn 3.1: Synset('lexington.n.03') ['Lexington', 'Concord', 'Lexington_and_Concord'] the first battle of the American Revolution (April 19, 1775)
    Wn 2021: Synset('battles_of_lexington_and_concord.n.01') ['Battles_of_Lexington_and_Concord', 'Lexington', 'Concord', 'Lexington_and_Concord'] the first battle of the American Revolution (April 19, 1775)

```

7277 (6.18%) Synset id. wordnumbers from Wn 3.1 changed in Wn 2021
These are caused by the new ordering of synsets in the index.POS* files, for ex.:

```
Key mindless%5:00:00:meaningless:00
    Wn 3.1: Synset('mindless.s.01') ['mindless'] lacking the thinking capacity characteristic of a conscious being
    Wn 2021: Synset('mindless.s.02') ['mindless'] lacking the thinking capacity characteristic of a conscious being; the shrieking of the mindless wind

Key fighting_joe_hooker%1:18:00::
    Wn 3.1: Synset('hooker.n.01') ['Hooker', 'Joseph_Hooker', 'Fighting_Joe_Hooker'] United States general in the Union Army who was defeated at Chancellorsville by Robert E. Lee (1814-1879)
    Wn 2021: Synset('hooker.n.04') ['Hooker', 'Joseph_Hooker', 'Fighting_Joe_Hooker'] United States general in the Union Army who was defeated at Chancellorsville by Robert E. Lee (1814-1879)

Key vocalist%1:18:00::
    Wn 3.1: Synset('singer.n.01') ['singer', 'vocalist', 'vocalizer', 'vocaliser'] a person who sings
    Wn 2021: Synset('singer.n.03') ['singer', 'vocalist', 'vocalizer', 'vocaliser'] a person who sings

```

**Comment by mirfan899** [comment]
thanks for redirecting. I'm getting the error after updating `nltk` from latest develop branch and using latest http://john.mccr.ae/oewn2021/english-wordnet-2021.zip
```python
from nltk.corpus import wordnet2021

synsets = wordnet2021.all_synsets()
output = []

for synset in synsets:
    try:
        lemmas = wordnet2021.synset(synset._name).lemmas()
        for lemma in lemmas:
            t = lemma.synset()._name.split(".")[1]
            key = lemma.key()
            r = str(wordnet2021.ss2of(lemma.synset()))
            offset = r[:r.index("-")] + t
            output.append(key + " " + "wn:" + offset)
    except:
        print(synset, "name Not found==================================================")

with open("sensekeys2offsets.txt", "w") as writer:
    for line in output:
        writer.write(line + "\n")

```
Here is the error.

```shell
Traceback (most recent call last):
  File "/home/irfan/PycharmProjects/StreusleSpacy/sensekeys2offsets.py", line 16, in <module>
    for synset in synsets:
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1721, in all_synsets
    synset = from_pos_and_line(pos_tag, line)
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1513, in _synset_from_pos_and_line
    frame_string_fmt = VERB_FRAME_STRINGS[frame_number]
IndexError: tuple index out of range

```

**Comment by ekaf** [comment]
The code above by @mirfan899 would run smoothly with the updated WNDB, if the following out-of range frame numbers were fixed. Isn't it surprising that such trivial bugs have not been stopped earlier?

```
Frame number 36 too high for 2764181-v
Frame number 37 too high for 2768667-v
Frame number 38 too high for 2768981-v
Frame number 39 too high for 2771745-v

```

**Comment by goodmami** [comment]
> if the following out-of range frame numbers were fixed. Isn't it surprising that such trivial bugs have not been stopped earlier?

OEWN 2021 has 39 subcategorization frames instead of WordNet's 35. It seems the proper fix is for `nltk.corpus.wordnet2021` to augment the `VERB_FRAME_STRINGS` data structure with the 4 new ones to avoid the `IndexError`.

Also, side note, the module name `wordnet2021` is not accurate as it is not a new version of WordNet, but I agree that `openenglishwordnet2021` is a bit long and `oewn2021` a bit opaque. I'm pretty sure you're aware of the trademark issue, but also users of NLTK might misattribute the data to Princeton if it's just called `wordnet2021`.

**Comment by 1313ou** [comment]
All this fuss (and need for extra code) for 4 verb frames that occur only **ONCE** (hardly a subcategorization then, is it?):

- via-out-of
- via-for
- via via-on-anim
- via via-at 

```
<Sense id="oewn-scare_the_bejesus__2.37.01.." n="0" subcat="via-out-of" synset="oewn-91001671-v"/>
<Sense id="oewn-fix__2.36.02.." n="12" subcat="via-for" synset="oewn-90000281-v"/>
<Sense id="oewn-hate__2.32.01.." n="1" subcat="via via-on-anim" synset="oewn-90017091-v"/>
<Sense id="oewn-mug__2.39.01.." n="1" subcat="via via-at" synset="oewn-90015901-v"/>

```
They join Prince William, Duke of Cumberland, Capital: Critique of Political Economy and Yahoo! in the list of oddities
see https://github.com/globalwordnet/english-wordnet/issues/167

Is this worth breaking legacy code? 

NB The grinder I have written produces a wndb_compat preview version of oewn2021 that works as a seamless stand-in replacement of PWN and passes @ekaf 's test with the **current** nltk lib (that uses hardwired verb frames).
https://github.com/x-englishwordnet/wndb
To be announced after oewn2021 comes out.

**Comment by ekaf** [comment]
Interesting dict, @1313ou ! I confirm that it doesn't have the frame problem. It also passes the "Bad key" test, just as OEWN's latest WNDB release also does. However, running the https://github.com/globalwordnet/english-wordnet/files/7459290/synchanged.py.txt  script produces more changed wordnumbers due to the index.POS* files not respecting the sense ranking frequencies: where WNDB has 7277, yours has 7938. In my opinion, this is a problem worth some "fuss":

```
15 (0.01%) lemmas from Wn 3.1 changed in Wn 3.1
2124 (1.8%) Synset id. wordnames from Wn 3.1 changed in Wn 3.1
7938 (6.74%) Synset id. wordnumbers from Wn 3.1 changed in Wn 3.1

```

NB: NLTK perceives your version as "3.1" because it extracts the version number from the 1740 bytes license text in data.adj

**Comment by jmccrae** [comment]
I removed the links to frames > 35 in the WNDB version.

**Comment by ekaf** [comment]
There has been a lot of discussion around issue #747, since it was closed two weeks ago. Maybe it deserves reopening temporarily?

Concerning @goodmami's judicious remarks (https://github.com/globalwordnet/english-wordnet/issues/747#issuecomment-958638337), hardcoding the verb frames as NLTK does is an NLTK bug. An issue should be raised there, but the newer verb frames should also be added to the _verb.Framestext_ file, as in @1313ou's wndb distribution (https://github.com/x-englishwordnet/wndb), which is right now superior to the official OEWN export.

I have been thinking along the same lines as @goodmami, weighing advantages against drawbacks in calling the NLTK package 'wordnet2021'. There is no legal issue, since Princeton no longer holds a trademark in the WordNet name. Perhaps @jmccrae has some preference concerning the NLTK package name?

**Comment by goodmami** [comment]
> hardcoding the verb frames as NLTK does is an NLTK bug. An issue should be raised there, but the newer verb frames should also be added to the `verb.Framestext` file

That would be a better fix, but note that the NLTK distribution of WordNet 3.0 does not include `verb.Framestext`, so the hardcoded values should be used for that data, while wn31 or OEWN 2021 could load them dynamically.

**Comment by jmccrae** [comment]
Hi all, I am at this point satisfied that the issues with the release are now only minor. The XML and RDF versions appear to be completely stable, the WNDB is still a little problematic but it is not possible to accommodate all modifications made by this project relative to this legacy format. It would IMHO be better if NLTK and other tools moved to the XML format that is more stable.

Can I ask you all to please stop posting to this issue? Instead, please create new issues (using the "Release format issue" template).

I will post an announcement of the release to Corpora List, Linguist List, WN Users and some social media on Sunday. 

I would like to thank you all for you contributions, it has all been incredibly useful and I think we can all be proud of how much we have achieved with this release.
