### ISSUE TITLE
pack of wolves and dogs

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#753]
**Affected synsets**

`wolf pack` is given as a hyponym of `pack`, but a domestic dog is only 'meronym' for `pack`

**Proposed changes**

Remove wolf pack?

**Motivation**

What about other https://en.wikipedia.org/wiki/Collective_noun that may be inconsistently encoded?

**Comment by jmccrae** [comment]
This is clearly compositional and wouldn't be worthy of inclusion if it was a new sense, but I am not so in favour of deleting existing synsets that may be useful for other projects. 

The meronym of 'pack' should probably refer to something more general like 'canine' so that it can also include wolves
