### ISSUE TITLE
Wrong hypernyms for some tree types

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#78]
For some types of trees the hypernym is incorrect. The synsets are

11661096-n
(n) sequoia, redwood 
>either of two huge coniferous California trees that reach a height of 300 feet; sometimes placed in the Taxodiaceae

11654084-n 
(n) cypress pine 
> any of several evergreen trees or shrubs of Australia and northern New Caledonia

11657017-n (Interlingual Index: i98522)
(n) juniper 
> coniferous shrub or small tree with berrylike cones

11662414-n (Interlingual Index: i98548)
(n) swamp cypress, Taxodium distichum, pond bald cypress, southern cypress, bald cypress 
> common cypress of southeastern United States having trunk expanded at base; found in coastal swamps and flooding river bottoms

11662694-n (Interlingual Index: i98549)
(n) pond cypress, Taxodium ascendens, bald cypress 
> smaller than and often included in the closely related Taxodium distichum

11662881-n (Interlingual Index: i98550)
(n) Montezuma cypress, Mexican swamp cypress, Taxodium mucronatum 
> cypress of river valleys of Mexican highlands

In all cases the hypernym is given as:

11651341-n (Interlingual Index: i98493)
(n) cypress 
> wood of any of various cypress trees especially of the genus Cupressus

But should be:

11650940-n (Interlingual Index: i98492)
(n) cypress, cypress 
> tree any of numerous evergreen conifers of the genus Cupressus of north temperate regions having dark scalelike leaves and rounded cones

Thanks to Itziar Gonzalez for reporting

**Comment by jmccrae** [comment]
I am pushing this to 3.3 as it is more difficult. The existing synsets should be preserved but there should be new synsets for the trees themselves. Each of the definitions should be updated by adding "wood from" to the front of the definition.

**Comment by jmccrae** [comment]
Solution is to add 'wood from' in front of the definition of each synset and introduce a new synset as a hyponym of `ewn-11650940-n` with the previous definition.

**Comment by ekaf** [comment]
In PWN 3.1, these cypresses are trees, but wrongly linked as hyponyms of cypress2 (cypress wood), although they should be hyponyms of cypress1 (cypress tree). Unfortunately, handling this issue necessarily results in sense key violations, because it involves an essential change of meaning, but it is unavoidable since these trees have a wrong hypernym in PWN, which needs to be corrected.

Both Wikipedia and Wiktionary only define cypress as tree, and not as wood. So the alternative solution may be worse, because changing the definitions also violates the referential integrity of the sense keys, but additionally, creating new senses for each type of wood can become unwieldy, especially if it needs to be done with every possible tree sort.

**Comment by jmccrae** [comment]
Okay, so either way it seems that there will be some confusion if we re-use sense keys from the previous version. I am going to assign new sense keys to each of these senses and require users to disambiguate the meaning if they wish to keep version integrity.
