### ISSUE TITLE
Split synset 05881364-n

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#8]
The synset (05881364-n) contains some inconceived terms:

ABCs, first principles, ABC's, alphabet, rudiments, ABC

Propose splitting it into two synsets

**Comment by jmccrae** [comment]
Other dictionaries support this meaning
https://www.lexico.com/definition/abc
https://www.dictionary.com/browse/abc-s

We should add 'ABC', 'ABCs', 'ABCs' to `ewn-06509450-n` ('alphabet')

**Comment by arademaker** [comment]
not sure if I understood the point.

**Comment by jmccrae** [comment]
I am honestly not sure where this original report came from (it could be me!).

The issue is that the only results for 'ABCs' is this synset (basic principles). It should probably also give the literal meaning of 'alphabet', hence adding the lemmas to the existing 'alphabet' synset.

I was also not sure if 'ABCs' is a good synonym of 'rudiments', but I can't give any good reason that it isn't, so I think we should leave it.

**Comment by jmccrae** [comment]
Moving to 2021 as there is not agreement

**Comment by dcillessen** [comment]
I agree that ABC's should be left where it is. It is informal to use "ABCs" in this way, but it is common enough at least in North America to qualify as everyday speech. We shouldn't add "ABC's" to "alphabet" because "alphabet" may be used to describe a multitude of languages while "ABCs" has a more specific linguistic context. 

That being said, I think there is a case for removing "alphabet" from synset 05881364-n. I can imagine somebody saying that they are "learning the _ABC's_ of underwater basket weaving," but saying that they are "learning the _alphabet_ of underwater basket weaving" comes across strangely.  

Other dictionaries like [Webster's (2)](https://www.merriam-webster.com/dictionary/alphabet) and [AH (3)](https://www.ahdictionary.com/word/search.html?q=alphabet) describe "alphabet" as beyond simply sets of letters for use in language, and describes "alphabets" instead as systems of elemental information (as is the case in the genetic "alphabet"). Interestingly, this doesn't appear in the OED's entry on the noun form of "alphabet," so it may be particular to American English. 

I think that including "alphabet" in 05881364-n is an attempt to hold on to the meaning described above (a system of symbols), but it does so imperfectly.  Unfortunately, we can't easily solve this problem by expanding the definition of "alphabet" (06509450-n) due to its placement within a hierarchy of strictly language-related nouns. 

Ultimately my proposal is to move "alphabet" out of [ewn-05881364-n](https://en-word.net/lemma/alphabet) (rudiments. . . ), and add it to [ewn-06820707-n](https://en-word.net/lemma/symbolism) ("symbolism" defined as "a system of symbols and symbolic representations").  This sorts out the different senses which are currently muddled together.

**Comment by Ciara97olo** [comment]
"ABCs" moved to "alphabet", as it is commonly placed with alphabet in other dictionaries such as: https://dictionary.cambridge.org/dictionary/english/abcs 

The definition of ewn-06820707-n is too broad to add "alphabet" to the synset, alphabet could not be in this synset without "letters", in which case there would need to be a specific synset for symbolic markings that represent spoken language and communicate information. 

In relation to "ABCs" and "rudiment", ABCs removed from this synset as "rudiments" and "first principles" are used to define "ABCs" in other dictionaries, but "ABCs" is not used to define either of these terms. https://www.merriam-webster.com/dictionary/rudiment
https://dictionary.cambridge.org/dictionary/english/rudiments
https://www.collinsdictionary.com/dictionary/english/rudiment
